;;; ripgrep-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ripgrep.el

(autoload 'ripgrep-regexp "ripgrep" "\
Run a ripgrep search with `REGEXP' rooted at `DIRECTORY'.
`ARGS' provides Ripgrep command line arguments.

(fn REGEXP DIRECTORY &optional ARGS)" t)
(register-definition-prefixes "ripgrep" '("ripgrep"))

;;; End of scraped data

(provide 'ripgrep-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ripgrep-autoloads.el ends here
