;;; py-autopep8-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from py-autopep8.el

(autoload 'py-autopep8-buffer "py-autopep8" "\
Use the \"autopep8\" tool to reformat the current buffer.
Return non-nil if the buffer was modified." t)
(function-put 'py-autopep8-buffer 'important-return-value 'nil)
(autoload 'py-autopep8-region "py-autopep8" "\
Use the \"autopep8\" tool to reformat whole lines in the region (BEG, END).
Return non-nil if the buffer was modified.

(fn BEG END)" t)
(function-put 'py-autopep8-region 'important-return-value 'nil)
(autoload 'py-autopep8-mode "py-autopep8" "\
Py-autopep8 minor mode.

This is a minor mode.  If called interactively, toggle the `Py-Autopep8
mode' mode.  If the prefix argument is positive, enable the mode, and if
it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `py-autopep8-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
(register-definition-prefixes "py-autopep8" '("py-autopep8-"))

;;; End of scraped data

(provide 'py-autopep8-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; py-autopep8-autoloads.el ends here
