#!/bin/bash

[[ $1 == -yy ]] && ALL_YES=1 || ALL_YES=

#########
#  VIM  #
#########

REPLY=0
[[ -n $ALL_YES ]] || read -p "Setup vim? [0] Full vim install -- (1) minimal vim install" -n 1 -r
echo ""
if [[ -n $ALL_YES ]] || [[ $REPLY == 0 ]]
then
    curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    if command -v nvim &> /dev/null; then
        echo "Bootstraping Vim"
        nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
    fi
else
    echo "setting up minimal vim"
    ln -sf ~/.vim/vimrc-mini ~/.vimrc
fi


#############
#  XModmap  #
#############

# Clearing the caps lock key
if uname -o|grep Linux &> /dev/null; then
    xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
fi

#########
#  FZF  #
#########

[[ -n $ALL_YES ]] || read -p "Setup fzf? [yN] " -n 1 -r
echo ""
if [[ -n $ALL_YES ]] || [[ $REPLY =~ ^([Yy]|yes)$ ]]
then
    if type fzf &> /dev/null; then
        mkdir -p $HOME/.config/fzf
        for shell in bash zsh; do
            ln -sf /usr/share/fzf/key-bindings.${shell} $HOME/.config/fzf/
            ln -sf /usr/share/fzf/completion.${shell} $HOME/.config/fzf/
        done
    else
        echo "fzf is not installed."
    fi
fi

#########################
#  Tmux plugin manager  #
#########################

[[ -n $ALL_YES ]] || read -p "Setup Tmux plugin manager? [yN] " -n 1 -r
echo ""
if [[ -n $ALL_YES ]] || [[ $REPLY =~ ^([Yy]|yes)$ ]]
then
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

# wget https://github.com/sindresorhus/pure/blob/master/pure.zsh
# wget https://github.com/sindresorhus/pure/blob/master/async.zsh


###################
#  diff-so-fancy  #
###################

echo ""
echo "========================"
echo "Installing diff-so-fancy"
wget -O $HOME/bin/diff-so-fancy https://raw.githubusercontent.com/so-fancy/diff-so-fancy/master/third_party/build_fatpack/diff-so-fancy && \
    chmod 744 $HOME/bin/diff-so-fancy

# Change to zsh default shell
echo ""
echo "=============="
echo "Installing zsh"
if [ -e /usr/bin/zsh ]; then
   chsh -s /usr/bin/zsh
    # Install oh-my-zsh
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi
