---

- name: Install packages
  package:
    name:
      - afew
      - alacritty
      - alot
      - base-devel
      - bash-language-server
      - bat
      - bc
      - clang
      - cmake
      - ctags
      - docker
      - docker-compose
      - duf
      - fd
      - fzf
      - git
      - gnome-keyring # Required for applications to store secrets
      - htop
      - inetutils
      - inkscape
      - isync
      - jq
      - lf
      - libsecret # Required for applications to access secrets
      - lightdm #enable systemd afterwards
      - lightdm-webkit2-greeter
      - lua-language-server
      - lynx
      - msmtp
      - ncdu
      - neovim
      - networkmanager
      - networkmanager-openconnect
      - networkmanager-openvpn
      - nextcloud-client
      - notmuch
      - nvidia
      - obs-studio
      - openssh
      - pavucontrol # sound
      - pulseaudio
      - pulseaudio-alsa
      - python-pip
      - ripgrep
      - rofi
      - signal-desktop
      - task
      - thunderbird
      - tig
      - tmux
      - ttf-dejavu # to get a correct monospace font
      - transmission-gtk
      - ulauncher
      - vdirsyncer
      - vlc
      - wget
      - x-arc-shadow
      - xclip
      - xfce4
      - xfce4-goodies
      - yay
    state: present
    update_cache: true


    #> In AUR
    #      - bitwarden-bin
    #      - bitwarden-cli
    #      - cadmus-deb
    #      - nerd-fonts-hack
# vi:ft=yaml.ansible
