;;; vimish-fold-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from vimish-fold.el

(autoload 'vimish-fold "vimish-fold" "\
Fold active region staring at BEG, ending at END.

(fn BEG END)" t)
(autoload 'vimish-fold-unfold "vimish-fold" "\
Delete all `vimish-fold--folded' overlays at point." t)
(autoload 'vimish-fold-refold "vimish-fold" "\
Refold unfolded fold at point." t)
(autoload 'vimish-fold-delete "vimish-fold" "\
Delete fold at point." t)
(autoload 'vimish-fold-unfold-all "vimish-fold" "\
Unfold all folds in current buffer." t)
(autoload 'vimish-fold-unfold-all-others "vimish-fold" "\
Unfold all but current folds in current buffer." t)
(autoload 'vimish-fold-refold-all "vimish-fold" "\
Refold all closed folds in current buffer." t)
(autoload 'vimish-fold-refold-all-others "vimish-fold" "\
Refold all closed folds but current in current buffer." t)
(autoload 'vimish-fold-delete-all "vimish-fold" "\
Delete all folds in current buffer." t)
(autoload 'vimish-fold-delete-all-others "vimish-fold" "\
Delete all folds but current in current buffer." t)
(autoload 'vimish-fold-toggle "vimish-fold" "\
Toggle fold at point." t)
(autoload 'vimish-fold-toggle-all "vimish-fold" "\
Toggle all folds in current buffer." t)
(autoload 'vimish-fold-toggle-all-others "vimish-fold" "\
Toggle all folds but current in current buffer." t)
(autoload 'vimish-fold-avy "vimish-fold" "\
Fold region of text between point and line selected with avy.

This feature needs `avy' package." t)
(autoload 'vimish-fold-next-fold "vimish-fold" "\
Jump to next folded region in current buffer." t)
(autoload 'vimish-fold-previous-fold "vimish-fold" "\
Jump to previous folded region in current buffer." t)
(autoload 'vimish-fold-narrow-to-fold "vimish-fold" "\
Narrow to fold at current position." t)
(autoload 'vimish-fold-from-marks "vimish-fold" "\
Create folds from folding symbols.

Mark strings are controlled by `vimish-fold-marks' customize variable." t)
(autoload 'vimish-fold-mode "vimish-fold" "\
Toggle `vimish-fold-mode' minor mode.

With a prefix argument ARG, enable `vimish-fold-mode' mode if ARG
is positive, and disable it otherwise.  If called from Lisp,
enable the mode if ARG is omitted or NIL, and toggle it if ARG is
`toggle'.

This minor mode sets hooks so when you `find-file' it calls
`vimish-fold--restore-folds' and when you kill a file it calls
`vimish-fold--save-folds'.

For globalized version of this mode see `vimish-fold-global-mode'.

(fn &optional ARG)" t)
(put 'vimish-fold-global-mode 'globalized-minor-mode t)
(defvar vimish-fold-global-mode nil "\
Non-nil if Vimish-Fold-Global mode is enabled.
See the `vimish-fold-global-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `vimish-fold-global-mode'.")
(custom-autoload 'vimish-fold-global-mode "vimish-fold" nil)
(autoload 'vimish-fold-global-mode "vimish-fold" "\
Toggle Vimish-Fold mode in all buffers.
With prefix ARG, enable Vimish-Fold-Global mode if ARG is positive;
otherwise, disable it.

If called from Lisp, toggle the mode if ARG is `toggle'.
Enable the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

Vimish-Fold mode is enabled in all buffers where `vimish-fold-mode'
would do it.

See `vimish-fold-mode' for more information on Vimish-Fold mode.

(fn &optional ARG)" t)
(register-definition-prefixes "vimish-fold" '("vimish-fold-"))

;;; End of scraped data

(provide 'vimish-fold-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; vimish-fold-autoloads.el ends here
