;;; affe-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from affe.el

(autoload 'affe-grep "affe" "\
Fuzzy grep in DIR with optional INITIAL input.

(fn &optional DIR INITIAL)" t)
(autoload 'affe-find "affe" "\
Fuzzy find in DIR with optional INITIAL input.

(fn &optional DIR INITIAL)" t)
(register-definition-prefixes "affe" '("affe-"))


;;; Generated autoloads from affe-backend.el

(register-definition-prefixes "affe-backend" '("affe-backend--"))

;;; End of scraped data

(provide 'affe-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; affe-autoloads.el ends here
