;;; projectile-ripgrep-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from projectile-ripgrep.el

(autoload 'projectile-ripgrep "projectile-ripgrep" "\
Run a Ripgrep search with `SEARCH-TERM' rooted at the current projectile project root.

With an optional prefix argument `ARG' `SEARCH-TERM' is interpreted as a
regular expression.

(fn SEARCH-TERM &optional ARG)" t)

;;; End of scraped data

(provide 'projectile-ripgrep-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; projectile-ripgrep-autoloads.el ends here
