;;; company-auctex-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from company-auctex.el

(autoload 'company-auctex-macros "company-auctex" "\
company-auctex-macros backend

(fn COMMAND &optional ARG &rest IGNORED)" t)
(autoload 'company-auctex-symbols "company-auctex" "\
company-auctex-symbols backend

(fn COMMAND &optional ARG &rest IGNORED)" t)
(autoload 'company-auctex-environments "company-auctex" "\
company-auctex-environments backend

(fn COMMAND &optional ARG &rest IGNORED)" t)
(autoload 'company-auctex-labels "company-auctex" "\
company-auctex-labels backend

(fn COMMAND &optional ARG &rest IGNORED)" t)
(autoload 'company-auctex-bibs "company-auctex" "\
company-auctex-bibs backend

(fn COMMAND &optional ARG &rest IGNORED)" t)
(autoload 'company-auctex-init "company-auctex" "\
Add backends provided by company-auctex to company-backends.")
(register-definition-prefixes "company-auctex" '("car-or" "company-auctex-"))

;;; End of scraped data

(provide 'company-auctex-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; company-auctex-autoloads.el ends here
