;;; python-environment-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from python-environment.el

(register-definition-prefixes "python-environment" '("python-environment-"))


;;; Generated autoloads from test-python-environment.el

(register-definition-prefixes "test-python-environment" '("pye-"))

;;; End of scraped data

(provide 'python-environment-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; python-environment-autoloads.el ends here
