#!/bin/bash

read -p "Setup vim? [yN] " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]
then
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    if command -v vim &> /dev/null; then
        echo "Bootstraping Vim"
        ln -s ~/.vim/vimrc ~/.vimrc
        vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
    fi

fi

curl https://raw.githubusercontent.com/mitsuhiko/pipsi/master/get-pipsi.py | python
ln -s ~/.local/venvs/pipsi/bin/virtualenv ~/.local/bin/virtualenv

yadm decrypt
